---
- name: copy files from one directory to another directory
  hosts: localhost
  become: yes

  tasks:
  - name: copying files from one directory to another
    copy:
      src: /home/mahesh/ansible/users.yml
      dest: /home/mahesh/Ansible-Training
  