---
- name: test yaml playbook
  hosts: web
  become: true

  tasks:
    - name: Nginx package download
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Starting the service
      ansible.builtin.service:
        name: nginx
        state: started