---
- name: installing a packages using loop
  hosts: web
  become: true

  tasks:
    - name: installing a series of packages with loops
      ansible.builtin.apt:
        name: "{{ item }}"

      loop:
        - git
        - wget
        - curl
        - tree
        - figlet
    - name: executing a command using the command module
      ansible.builtin.command: figlet "Happy New Year 2K26"