---
- name: vars session started
  hosts: web
  become: true

  vars_files: 
    - vars.yml

  tasks:
    - name: using vars installing the package
      ansible.builtin.apt:
        name: "{{ pkg_name }}"
    
    - name: creating a file
      ansible.builtin.file:
        name: "{{ file_name }}"
        state: touch

    - name: content for the file
      ansible.builtin.copy:
        dest: /home/ubuntu/mahesh.html
        content: |
          heyyy these is for You 11.